language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
  - composer selfupdate
  - composer update $COMPOSER_FLAGS

script:
  - echo '[phpspec] Running specification tests'; ./vendor/bin/phpspec run -n -f dot
  - output=$(php -n php-cs-fixer.phar fix -v --dry-run --config=sf23 .); if [[ $(grep -o F <<< $output | wc -l) -gt 3 ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;
